### ISSUE TITLE
FEAT - bucketDetail 버킷 컴포넌트 생성

### ISSUE THREAD

**Issue by Nahyeonnnn** [pda-dongdonge/dongdong-front#1]
## 💡 Feature issue
- 레퍼런스에 있었던 가장 상단 버킷 설명 컴포 구현

![image](https://github.com/pda-dongdonge/dongdong-front/assets/117283341/83055c7c-05f8-436f-8bf9-241f108e5a32)

## ✅ To-do
- [x] 이미지 배치 (최대 6개)
- [x] 좋아요 기능 (클릭 시 활성화 이벤트)
- [x] 버킷 기본 정보 배치 (생성 유저, 간단 설명, 뷰 수 등)
