### ISSUE TITLE
FEAT - 유저 페이지 버킷리스트 & api연결 

### ISSUE THREAD

**Issue by soyalattee** [pda-dongdonge/dongdong-front#10]
## 💡 Feature issue
- 유저 페이지 버킷리스트 디자인 
- 유저 페이지 post 팔로우, get 팔로잉,팔로워, get버킷리스트, get 좋아요한 버킷리스트

## ✅ To-do
- [x] 유저 페이지 버킷리스트 디자인
- [x] get 해당 유저 정보(아이디 조회 -> 닉네임 등 ) 
- [x] get 팔로잉 팔로워
- [x] get 좋아요한 버킷
- [x] user feed 버킷
- [x] get 해당 유저 버킷 
- [x] 버킷 클릭시 해당 버킷 이동 
- [ ] 프로필 dummy image 적당한 이미지 url 찾기 (이쁜거)
