### ISSUE TITLE
FEAT - bucketDetail page 개별 bucketItem 컴포넌트 구현

### ISSUE THREAD

**Issue by Nahyeonnnn** [pda-dongdonge/dongdong-front#16]
## 💡 Feature issue
- bucketItemList, bucketItem 컴포넌트 구현
![image](https://github.com/pda-dongdonge/dongdong-front/assets/117283341/d81fdd8e-8d30-44ef-b56e-bf645e029cb5)

## ✅ To-do
- [x] 개별 버킷 조회 bucket/detail/:bucektId -> api 연결해서 버킷 정보 받아오기
- [x] bucketItem에 img, contents(설명) 간략한 정보 띄우기
- [x] bucket에 좋아요 기능 추가 -> api 연결 필요
- [x] 공유 버튼 클릭 시 토스트 팝업과 함께 클립보드에 복사 기능 추가
- [x] 유저 정보 띄우기
