### ISSUE TITLE
FEAT  - user page UI

### ISSUE THREAD

**Issue by soyalattee** [pda-dongdonge/dongdong-front#2]
## 💡 Feature issue
- user page UI 작업 

## ✅ To-do
- [x] user page 라우터 분리 
- [x] tab (bucket, feed) 구분하기
- [x] 유저 정보 UI 생성
