### ISSUE TITLE
FEAT - 유저 페이지 자잘한 기능 추가 

### ISSUE THREAD

**Issue by soyalattee** [pda-dongdonge/dongdong-front#38]
## 💡 Feature issue
- 유저 페이지 디테일 추가 

## ✅ To-do
- [x] 양동이에 하트 추가
- [x] 양동이 링크 복사
- [x] 유저 링크 복사
- [x] more버튼 클릭시 아직없는 기능이에요 팝업 
- [x] 내  버킷이면 텅 에다가 새로운 버킷 추가하기 버튼추가(바로 추가할 수 있게)
