### ISSUE TITLE
FIX: 자잘한 이슈 수정 

### ISSUE THREAD

**Issue by soyalattee** [pda-dongdonge/dongdong-front#45]
## 💡 Feature issue
- 테스트 하면서 이슈 수정 

## ✅ To-do
- [ ] feed 페이지에 팔로우한 사람이 없을때 텅 노출 
- [x] nav bar 화면 작을때 로고 작아지는것 수정
- [x] 네비 위치 수정 
- [ ] 버킷 위치 중앙정렬,  gird로 변경하고 gap 일정하게 하기 
- [ ] 하트 누르면 바로 반영 
- [x] 디테일 페이지도 가운데 정렬 (iphone se기준)
- [x]  모달 가운데 정렬
