### ISSUE TITLE
FEAT - USER 로그인&회원가입 UI 연결

### ISSUE THREAD

**Issue by soyalattee** [pda-dongdonge/dongdong-front#7]
## 💡 Feature issue
- 로그인 & 회원가입 기능과 UI를 연결

## ✅ To-do
- [x] 로그인페이지 API 연결
- [x] 회원가입페이지 API 연결 
- [x] 메뉴에 로그인 정보 표시 
- [x] 로그아웃 버튼 추가
- [x] 로그아웃 API 연결
- [x] 회원가입 이메일 중복확인 추가
